🥝 github tests actions 🥝

diff --git a/.github/workflows/run_tests.yaml b/.github/workflows/run_tests.yaml
--- a/.github/workflows/run_tests.yaml
+++ b/.github/workflows/run_tests.yaml
@@ -48,13 +48,13 @@ jobs:
           while test 0 == $(oc -n ${repo##*/}-test get pod -l run=$podname -o name 2>/dev/null | wc -l); do sleep 5; done
           oc -n ${repo##*/}-test wait pod -l run=$podname --for=condition=Ready --timeout=60s
 
-          while [ "$(oc get pods -l run=$podname -o jsonpath='{.items[*].status.phase}')" != "Failed" && "$(oc get pods -l run=$podname -o jsonpath='{.items[*].status.phase}')" != "Succeeded" ]; do
+          while [ "$(oc get pods -l run=$podname -o jsonpath='{.items[*].status.phase}')" != "Failed" -a "$(oc get pods -l run=$podname -o jsonpath='{.items[*].status.phase}')" != "Succeeded" ]; do
               echo "$podname phase is $(oc get pods -l run=$podname -o jsonpath='{.items[*].status.phase}') ..."
               sleep 5
           done
 
-          if [ "$(oc get pods -l run=$podname -o jsonpath='{.items[*].status.phase}')"=="Failed" ]; then
-            echo "🛑 test failed, exiting 🛑";
-                exit 1;
+          if [ "$(oc get pods -l run=$podname -o jsonpath='{.items[*].status.phase}')" != "Succeeded" ]; then
+              echo "🛑 test failed, exiting 🛑";
+              exit 1;
           fi
           echo "🦕 tests ran OK 🦕";
